### ISSUE TITLE
I get crashed out trying to do actions on Image server link

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1280]

**Comment by Sherlock21** [comment]
Testing the actions associated with Image Handling, I reported yesterday that I get crashed out whenI try to do Image DELETE
![Image Delete.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/545bc5c91920350200d20f63/125516c66e82c728ace21e0d46c1999b2487c38d8ae5ba57a11fbcd6395428792c07b7692ac7b67bba417a0456564aa4415f0d41fcfb892ba7b56970890a19f1c32f0e2a92624cf5f2d75dad0ba825894e84bcbd8f4cc3e93826ee8d89483f1e1755.jpg)

**Comment by SteveBiggs** [comment]
Bev wrote:
"I guess the cause is create/edit is allowed for admin/CC/SC only, I should display a warning message and exit, it is a bug found by Eric, I have pushed the change, once Kirk reviews, it will be deployed to test2."

**Comment by Captainkirkdawson** [comment]
Thank you EricB you have confirmed that it DOES NOT crash. A DM does not currently have permission to do that action.
Now that you have confirmed the code now traps the condition and does not crash we will give you permission

**Comment by Sherlock21** [comment]
Testing this same feature again today, I can now still see the same 4 actions: SH; ED; DE; LS.

Tried SH and that shows a list -OK.
Tried ED ( which had crashed out yesterday). Today I get screen message saying: Your account does not support this action.
But it does NOT crash out.

Tried DE and that gives same Message: Your account does not support this action.
Tried LS and that does navigate to another screen.

NOW this package works in a totally different way to the rest of FR as far as Profile of User is concerned.. In Fr, IfI can't do something because it's not in my profile, then I don't get to see the option on the list of actions.

HERE in Image handling, I do get the options shown but then can't do them.

Having one set of Logic rules in one part of the Application, and an opposite Logic in another bit is quite strange and will lead to much wasted time in the future by me -( and other users presumably depending on their profiles.
The logic throughout should be: if I can't do it, DONT show it.

**Comment by Captainkirkdawson** [comment]
Excellent point EricB we will take that into account.

**Comment by Captainkirkdawson** [comment]
@bev-fc  can you add DM as permitted to access action edit create and delete actions

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please take a look if it is okay.

**Comment by Sherlock21** [comment]
If that refers to me, and means Please test it out:

then No changes as far as I can tell - I still can't EDit or DElete

**Comment by Captainkirkdawson** [comment]
Tested and pulled into test2

**Comment by Sherlock21** [comment]
testing continued on new Do All Profile now.

tried Edit an Image Group - changed the range date OK 
added reason note - OK

HOWEVER: the date range I used was to 2205 ( i.e. well in future).SO question comes to mind: should this be checked to entire its a past date AND/OR a genuine date and not a spelling error?

Tried to Delete an Image. Got message: this Action is not currently supported. - is that right??

An issue though:
After doing each action hove, one gets thrown back to the state line of List Images under this group rather than to those images that one came from.

**Comment by Captainkirkdawson** [comment]
EricD. HOWEVER: the date range I used was to 2205 ( i.e. well in future).SO question comes to mind: should this be checked to entire its a past date AND/OR a genuine date and not a spelling error?
Did you test?? There are value controls in place

**Comment by Captainkirkdawson** [comment]
Delete action is correct at this time

**Comment by Sherlock21** [comment]
YES my 2205 year for the end date of a range of images was put into RF on Test2. on the top record. and it what's more it was accepted and stayed there till I got frozen out in the later bit of test as above. I have not been back since. So did your control not catch this one then?

**Comment by Captainkirkdawson** [comment]
This item is closed. Specific stories 1292 998 1283 987 replace
