### ISSUE TITLE
Image-source fields

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1281]
We need to show the original owner field in the source show. We have it in the edit

**Comment by Captainkirkdawson** [comment]
@bev-fc can you please action

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please take a look if it looks okay.

**Comment by Captainkirkdawson** [comment]
Tested and pulled into test2

**Comment by SteveBiggs** [comment]
What is the definition of the Original Owner here? Is it the OO of the original register (generally church) or of the fiche/film (generally RO) or of the photo (image) of the register/fiche?

**Comment by Captainkirkdawson** [comment]
Its what we decide. We provided 3 fields as each has "rights"

**Comment by SteveBiggs** [comment]
Under "Select if you want to propagate ....", please provide a "Select all" button and implement the ctrl-shift to select a range.

**Comment by bev-fc** [comment]
@SteveBiggs I think the change for #1287 I just pushed also clears your comment in this ticket, please correct me if I am wrong.

**Comment by SteveBiggs** [comment]
Yes, this issue is fixed, but #1287 has not been fixed yet, so I'm confused ....

**Comment by SteveBiggs** [comment]
I take that back - was looking on the wrong page. This issue in NOt fixed yet - I assume Kirk still needs to pull in?

**Comment by SteveBiggs** [comment]
That is what I assumed and have been doing, but Bev put in what looked like an action for me to check.

**Comment by SteveBiggs** [comment]
Despite #1287 being addressed, it has NOT fixed this. The problem is on the Edit Image Source page:
![capture](https://user-images.githubusercontent.com/25303607/29689633-c601222e-891b-11e7-9819-f5e041d971a6.jpg)

**Comment by Captainkirkdawson** [comment]
@bev-fc  having implemented the propagate image source action the code at the end of the edit needs to be removed
https://github.com/FreeUKGen/MyopicVicar/blob/bevbranch1/app/views/sources/_edit.html.erb#L27-L30

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed for Steve's latest comment, please verify if it works as expected, and if there is any mistake.

**Comment by Captainkirkdawson** [comment]
@bev-fc 
It is my impression that Steve was commenting that having introduced the Propagate Source action the select propagation at the end of the edit page is no longer required.

https://github.com/FreeUKGen/MyopicVicar/blob/bevbranch1/app/views/sources/_edit.html.erb#L27-L30

**Comment by SteveBiggs** [comment]
Actually my comment was to add a "Select all" button and implement the ctrl-shift to select a range, to the select propagation at the end of the edit page, but you're right that there is duplication of the propagate action.

**Comment by Captainkirkdawson** [comment]
Personally I prefer the separate actions. 
That allows the source to be edited a few times before being propagated! enables one to ensure that that is to be propagated is correct!

**Comment by SteveBiggs** [comment]
I agree.

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please take a look if it matches the requirement, and please let me know if you want any change or you see any mistake.

**Comment by Captainkirkdawson** [comment]
Looks fine; pulled into test2

**Comment by SteveBiggs** [comment]
Tested and works as expected.

**Comment by Sherlock21** [comment]
A fundamental question if i may please.

What exactly do your mean by Image Source?

Which image server its on?
OR where the fiches, film or Transcription came from?

like xxCounty RO,
or private collection
or publication by H Smith.

if they are all from which server, then there seems little purpose in the field. - or have I got it wrong again?

**Comment by edickens** [comment]
It is "where the fiches, film or Transcription came from".

**Comment by Sherlock21** [comment]
That is what I would have expected it to mean.
BUT picked at random from SSX, these are all Image Server or Image Server 1. Not one has been East Sussex RO of St johns church or anything! - mort confusing.
AND there is no way I can find that permits Edit the Source that is there. The tab called Edit Image Source does not have that facility in it!

![imagesource 1](https://user-images.githubusercontent.com/9368704/29750420-3b617722-8b37-11e7-8b88-cb65a5cb1079.jpg)

![imagesource 2](https://user-images.githubusercontent.com/9368704/29750422-42691a34-8b37-11e7-819d-82cab38fe7ee.jpg)

**Comment by Sherlock21** [comment]
![imagesource edit3](https://user-images.githubusercontent.com/9368704/29750442-7d146e04-8b37-11e7-8df9-923948985ced.jpg)

**Comment by Captainkirkdawson** [comment]
The Image Source for these images is the Image Server but there can be other Image Sources eg Ancestry.

The Image Source has fields that allow you to enter information as to where these images came from ie the Original Owner, Who created them, and who holds them. The images on the Image Server can come from many institutions

You cannot edit The Image Source field since it is the Image Server, or Ancestry or or

**Comment by edickens** [comment]
"Image Server" is the default when setting up the system.  SSX is a copy that their Records Office lent us of the images on their server.

**Comment by SteveBiggs** [comment]
So to further clarify for EricB, the "Image Server" is the FreeREG getscan server that transcribers download the images from to work on. This is the Image Source. All the SSX images are loaded on there. 

As EricD says, they came from WSRO and that is listed as the Holding Institution. They were filmed by the Genealogical Society (Creating Institution) and the original owner was the relevant Parish Church as listed on the Edit Source page you attached.

**Comment by Sherlock21** [comment]
Thank you all three.
But then, who other than Image Server will ever be the Image Source, and so merit having that field there in the first place?
The IS is really " The Last Port of Cal" in the image route isn't it?

**Comment by SteveBiggs** [comment]
It's wherever the transcriber gets/views the images from. For example in Essex, they pay and view them on the Essex RO website. In other counties such as Cornwall they're viewing directly on the FamilySearch website. Some coordinators put them on DropBox for the transcriber to download and not on the IS.
