### ISSUE TITLE
Add CC option to Contacts, Feedback and Message reply

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2086]
When sending a reply, as well as sending to the originator, add the means to send a copy to someone selected by UserID from the list of Active people.  Select from a drop down list with Ctl-Click to select more than one.
The reason is that the Coordinator replying may want to send the reply on to the transcriber, or to an assistant coordinator.

E0 U6 S7 C8; P21

**Comment by SteveBiggs** [comment]
I have also had requests to forward a Contact to an assistant coord or transcriber to deal with. Currently, this has to be done via personal email and there is no record that it's been addressed within the FR messaging system.

**Comment by edickens** [comment]
Yes.  But I would suggest that the responder could do a Reply to thank the sender and include a copy to the Assistant Coordinator.  A forwarding system is then not needed.
The copy should be bcc: no cc:.

**Comment by edickens** [comment]
Please can this be done soon?  For example in "reference 162223996" I need to reply to the sender and also send a copy to Mick as it is Lincolnshire question.  At present I need to use the contact system to reply to the sender and then use my mail to send a copy to Mick, but Mick will not be able to see the original message and any future correspondence.

**Comment by SteveBiggs** [comment]
Although a list of all userIDs is available to select for copying replies to, it appears from my testing that when one is selected, the reply message does not reach that user either within the FreeREG message system or to their email.

**Comment by Vino-S** [comment]
Hi @SteveBiggs ,
Fixed the issue. Also sorted the Userids list.
Please have a look and let me know your feedback

**Comment by SteveBiggs** [comment]
Email is now getting sent to the user on cc but the message is still not showing up in their 'My Messages' on the website.

**Comment by Vino-S** [comment]
Fixed: Ready for testing in test3

**Comment by DeniseColbert** [comment]
Ready for a test @SteveBiggs

**Comment by SteveBiggs** [comment]
There is no list of userIDs now to select for CC on Contacts or Feeback in test3. Also, I tried to do a test Contact as a researcher and it failed with no explanation as to why.

**Comment by DeniseColbert** [comment]
@SteveBiggs to try again

**Comment by SteveBiggs** [comment]
This appears to be working now.

**Comment by DeniseColbert** [comment]
Deployed; closing
